
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Over twee jaar wil ik me graag bezighouden met onderzoek over haematologie of oncologie, in combinatie met data science en zoölogie. Bij de minor Data Science leer ik verschillende vaardigheden en technieken, waardoor ik dit kan toepassen in mijn afstudeerstage en later in mijn werk. Ik zou graag willen werken bij een ziekenhuis of universiteit, met name onderzoek over ziektes en medicijnen. Voor mijn afstudeerstage zou ik graag onderzoek willen doen met proefdieren en medicijnen. Met Data Science kunnen we gegevens analyseren en inzichten uit halen, zoals verbeteren van diagnoses en ontdekken van nieuwe manieren om ziektes/ te bestrijden. 

Een nieuwe skill die ik graag wil leren is het visualiseren van data. Door nieuwe visualisatietools te ontdekken en toe te passen, zou ik in staat zijn om een nieuw type grafiek te maken en het visualiseren van mijn gegevens te vergemakkelijken. Voor de vrije ruimte ga ik de 'survival' package van R leren. 'Survival' package wordt gebruikt voor het visualiseren van overleveingsanalyses. Met deze package kan je de tijd tot overlijden of optreden van ziektes bestuderen. Dit is handig voor mijn afstudeerstage en op de werkveld. Met behulp van deze skill kan ik met interesse van haematologie/oncologie de verkregen data beter analyseren en gemakkelijker visualiseren.  

Om de 'survival' package in vier dagen te leren ga ik de volgende doen. Ten eerste ga ik papers en workflows opzoeken over de package. Met de informatie kan ik kennis vergroten en opzoeken wat ik nodig heb in de datasets. Een paper die ik ga bestuderen is bijvoorbeeld https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf. Ik ga op de internet nepdata of bestaande data opzoeken die gerelateerd is op onderzoeken van ziektes met overlevingskans of periode van overlijding. Ook ga ik op YouTube video's zoeken met uitleg over de gebruik van de package. 

| Dag 	| Planning 	|  	|  	|  	|
|---	|---	|---	|---	|---	|
| Dag 1  	| Inlezen van meerdere papers en websites met voorbeelden 	|  	|  	|  	|
| Dag 2 	| Bekijken van YouTube video's en zoeken naar workflows  	|  	|  	|  	|
| Dag 3 	| Zoeken van nepdata en begin maken met een script 	|  	|  	|  	|
| Dag 4 	| Verder aan script werken 	|  	|  	|  	|