---
title: "Portfolio"
author: "Rachel Breuer"
site: bookdown::bookdown_site
documentclass: book
bookdown::gitbook: default
link-citations: true
biblio-style: apalike
description: This is a minimal example of using the bookdown package to write a book.
  The output format for this example is bookdown::gitbook.
favicon: favicon32x32.png
bibliography: [citations.bib]
---

# Introductie {#section-id .unnumbered}
<body class="index-page">
Welkom op mijn pagina over data science! Ik ben Rachel Breuer, en ik studeer biologisch en medisch laboratorium aan de Hogeschool Utrecht, met een specialisatie in zoölogie en data science. Op deze website kun je een kijkje nemen naar mijn projecten en opdrachten.

In mijn portfolio deel ik verschillende onderzoeken en onderwerpen, zoals een experiment met C. elegans, een review van wetenschappelijke artikelen en onderzoek naar COVID-19. Hier laat ik ook zien welke R-packages ik graag wil leren, de 'survival' package, inclusief de resultaten en de bijbehorende code. Je vindt ook mijn zelfgemaakte package, package.rb, met alle benodigde informatie voor gebruik. Naast mijn projecten en opdrachten, kun je hier ook mijn persoonlijke groei als data scientist volgen. 
</body>
